### ISSUE TITLE
Semaine 8: du 11/11 au 18/11

### ISSUE THREAD

**Issue by dkrmr** [itheof/42sh-posix#52]
## Changements validés lors de la réunion
- [ ] Passage au C11: dfd7ab46a65e8d5ab0d8d32509edc893e869987b
- [ ] Utilisation de `errno`
- [ ] Analyseur statique de *Clang*

## ToDo:
- [ ] Faire la liste des tests d'intégration pour l'UI, @Otaekek 
- [ ] GCC build avec sanitize sous Linux, @itheof 
- [ ] Demander à Thor pour les fonctions du `man(3)` concernant l'environnement, @dkrmr

### Tokenizer module
* Devs: @tmielcza @dkrmr
* Review: @Otaekek @itheof 
- [ ] PR créée
- [ ] Review validée

### Alias/Unalias built-in
* Devs: @Kerollmops @itheof 
* Review: @dkrmr
- [ ] PR créée
- [ ] Review validée

### History built-in
* Devs: @Kerollmops @itheof 
* Review: @tmielcza 
- [ ] PR créée
- [ ] Review validée

### Getline
* Devs: @Kerollmops @itheof 
* Review: @Otaekek 
- [ ] PR créée
- [ ] Review validée

### UI module
* Devs: @Otaekek @tmielcza (Si nécessaire @Kerollmops)
* Review: @Kerollmops 
- [ ] PR créée
- [ ] Review validée

**Comment by dkrmr** [comment]
# Sujet à discuter Vendredi
* Passer le 42sh-posix en openproject ?
    * + Plus grande flexibilité sur les libs/fonctions: ncurses/getenv/perror/etc...
    * + Meilleure récompense en XP: T4 pour le 1er
    * - Contrainte de temps et de disponibilité
